name: Build PgBouncer-PS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
  
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: pgbouncer-ps

      - name: Checkout PgBouncer
        uses: actions/checkout@v3
        with:
          repository: pgbouncer/pgbouncer
          path: pgbouncer

      - name: Build
        uses: addnab/docker-run-action@v3
        with:
            image: centos:7
            options: -v ${{ github.workspace }}:/src
            run: |
                yum -y install libevent-devel openssl-devel python-devel libtool git patch make
                cd /src/pgbouncer-ps
                ./install-pgbouncer-ps-patch.sh ../pgbouncer
                cd ../pgbouncer
                git submodule init
                git submodule update
                ./autogen.sh
                ./configure
                make
