name: Build PgBouncer-PS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
  
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: pgbouncer-ps

      - name: Checkout PgBouncer
        uses: actions/checkout@v3
        with:
          repository: pgbouncer/pgbouncer
          ref: pgbouncer_1_18_0
          path: pgbouncer

      - name: Build EL7
        uses: addnab/docker-run-action@v3
        with:
            image: centos:7
            options: -v ${{ github.workspace }}:/src
            run: |
                yum -y install epel-release
                yum -y install libevent-devel openssl-devel python-devel libtool git patch make pandoc
                cd /src/pgbouncer-ps
                ./install-pgbouncer-ps-patch.sh ../pgbouncer
                cd ../pgbouncer
                git submodule init
                git submodule update
                ./autogen.sh
                ./configure
                make
                cd ..
                tar -czvf pgbouncer-ps-1.18.0.el7.x86_64.tar.gz pgbouncer/AUTHORS pgbouncer/COPYRIGHT pgbouncer/doc/pgbouncer.1 pgbouncer/doc/pgbouncer.5 pgbouncer/pgbouncer

      - name: Build EL8
        uses: addnab/docker-run-action@v3
        with:
            image: almalinux:8
            options: -v ${{ github.workspace }}:/src
            run: |
                yum -y install epel-release
                yum -y install libevent-devel openssl-devel python-devel libtool git patch make pandoc
                cd /src/pgbouncer-ps
                ./install-pgbouncer-ps-patch.sh ../pgbouncer
                cd ../pgbouncer
                git submodule init
                git submodule update
                ./autogen.sh
                ./configure
                make
                cd ..
                tar -czvf pgbouncer-ps-1.18.0.el8.x86_64.tar.gz pgbouncer/AUTHORS pgbouncer/COPYRIGHT pgbouncer/doc/pgbouncer.1 pgbouncer/doc/pgbouncer.5 pgbouncer/pgbouncer

      - name: Publish
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          automatic_release_tag: latest
          files: |
            *.tar.gz
